version: '3'
services:
  gryadka1:
    build: node-full
    privileged: true
    container_name: acceptor-proposer-1
    hostname: acceptor-proposer-1
    tmpfs:
      - /gryadka/mem
      - /gryadka/logs
    networks:
      - gryadkanet
  gryadka2:
    build: node-full
    privileged: true
    container_name: acceptor-proposer-2
    hostname: acceptor-proposer-2
    tmpfs:
      - /gryadka/mem
      - /gryadka/logs
    networks:
      - gryadkanet
  gryadka3:
    build: node-full
    privileged: true
    container_name: acceptor-proposer-3
    hostname: acceptor-proposer-3
    tmpfs:
      - /gryadka/mem
      - /gryadka/logs
    networks:
      - gryadkanet
  gryadka4:
    build: node-acceptor
    privileged: true
    container_name: acceptor-4
    hostname: acceptor-4
    tmpfs:
      - /gryadka/mem
      - /gryadka/logs
    networks:
      - gryadkanet
networks:
  gryadkanet:
    driver: bridge